### PR TITLE
feat: add landing page

### PR DESCRIPTION
**Pull request by gadgetfather**
I have created a landing page. Please review it.
link: https://z1f2e.csb.app/landing-page/index.html
image

### CODE REVIEW

**Review by VishalPatil18 — APPROVED** [review]
The landing page looks cool! 
In my opinion, typography can be improved by using a better font family, especially for headings or hero texts.

**Comment by mohammed-sas** [comment]
suggestion : if the texts and the buttons are centre aligned it would look better aesthetically

**Comment by VishalPatil18** [comment]
> The landing page looks cool! In my opinion, typography can be improved by using a better font family, especially for headings or hero texts.

The font-family in your screenshot is not matching to what I see on my screen. There might be a fix for that.
Screenshot 2022-02-01 at 11 01 36

**Comment by gadgetfather** [comment]
> > The landing page looks cool! In my opinion, typography can be improved by using a better font family, especially for headings or hero texts.
> 
> The font-family in the screenshot is not matching to what I see on my screen. There might be a fix for that. Screenshot 2022-02-01 at 11 01 36



> > The landing page looks cool! In my opinion, typography can be improved by using a better font family, especially for headings or hero texts.
> 
> The font-family in your screenshot is not matching to what I see on my screen. There might be a fix for that. Screenshot 2022-02-01 at 11 01 36

Sure will look into it, Thanks for pointing it out!

**Review by starver20 — APPROVED** [review]

**Pull request merged**
