### PR TITLE
feat: add utilities

### PR DESCRIPTION
**Pull request by gadgetfather**
I have created basic utilities. Please review them.
preview: https://gs9wg.csb.app/Utilities/utilities.html
image

### CODE REVIEW

**Review by Abhijeet43 — CHANGES_REQUESTED** [review]
hey class fs6 is missing?

**Comment by gadgetfather** [comment]
> hey class fs6 is missing?
Actually I have only 5 font sizes , so removed that extra line of code.
image

**Review by Ayushi20-19 — APPROVED** [review]
Good to go

**Review by Abhijeet43 — APPROVED** [review]
Code Looks fine now!!!

**Pull request merged**
